"""
Schemas package
"""

from .auth import (
    UserBase,
    UserRegister,
    UserLogin,
    UserResponse,
    UserProfile,
    TokenResponse,
    LoginResponse,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    UpdateProfileRequest,
    MessageResponse,
    ErrorResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
)

from .project import (
    ProjectStatus,
    ProjectMemberRole,
    ProjectMemberStatus,
    ProjectCreateRequest,
    ProjectUpdateRequest,
    ProjectResponse,
    ProjectSummary,
    ProjectDetail,
    ProjectListRequest,
    ProjectListResponse,
    ProjectStatusResponse,
    ProjectMemberResponse,
    ProjectMemberInviteRequest,
    ProjectMemberUpdateRequest,
    PaginationInfo,
    UserSummary,
    ProjectProgress,
    ProjectStatistics,
    ProjectActivity,
    ProjectError,
    ProjectNotFoundError,
    ProjectPermissionError,
    ProjectValidationError,
)

from .role import (
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleResponse,
    RoleListResponse,
    RoleReorderRequest,
    DefaultRoleTemplate,
    DefaultRolesResponse,
    RoleBulkCreateRequest,
    RoleBulkCreateResponse,
    RoleSearchRequest,
    RoleSearchResponse,
)

from .cta import (
    CTABase,
    CTACreate,
    CTAUpdate,
    CTAResponse,
    CTAListResponse,
    CTAMatrixCell,
    CTAMatrixRow,
    CTAMatrixResponse,
    CTABulkCreateRequest,
    CTABulkCreateResponse,
    CTASearchRequest,
    CTASearchResponse,
    UserStoryGenerateRequest,
    UserStoryResponse,
    CTAExportRequest,
    CTAValidationResult,
    CTAStatsResponse,
)

__all__ = [
    # Auth schemas
    "UserBase",
    "UserRegister", 
    "UserLogin",
    "UserResponse",
    "UserProfile",
    "TokenResponse",
    "LoginResponse",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "UpdateProfileRequest",
    "MessageResponse",
    "ErrorResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    
    # Project schemas
    "ProjectStatus",
    "ProjectMemberRole", 
    "ProjectMemberStatus",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectResponse",
    "ProjectSummary",
    "ProjectDetail",
    "ProjectListRequest",
    "ProjectListResponse",
    "ProjectStatusResponse",
    "ProjectMemberResponse",
    "ProjectMemberInviteRequest",
    "ProjectMemberUpdateRequest",
    "PaginationInfo",
    "UserSummary",
    "ProjectProgress",
    "ProjectStatistics",
    "ProjectActivity",
    "ProjectError",
    "ProjectNotFoundError",
    "ProjectPermissionError",
    "ProjectValidationError",
    
    # Role schemas
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleResponse",
    "RoleListResponse",
    "RoleReorderRequest",
    "DefaultRoleTemplate",
    "DefaultRolesResponse",
    "RoleBulkCreateRequest",
    "RoleBulkCreateResponse",
    "RoleSearchRequest",
    "RoleSearchResponse",
    
    # CTA schemas
    "CTABase",
    "CTACreate",
    "CTAUpdate",
    "CTAResponse",
    "CTAListResponse",
    "CTAMatrixCell",
    "CTAMatrixRow",
    "CTAMatrixResponse",
    "CTABulkCreateRequest",
    "CTABulkCreateResponse",
    "CTASearchRequest",
    "CTASearchResponse",
    "UserStoryGenerateRequest",
    "UserStoryResponse",
    "CTAExportRequest",
    "CTAValidationResult",
    "CTAStatsResponse",
]
