"""
Schemas package
"""

from .auth import (
    UserBase,
    UserRegister,
    UserLogin,
    UserResponse,
    UserProfile,
    TokenResponse,
    LoginResponse,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    UpdateProfileRequest,
    MessageResponse,
    ErrorResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
)

from .project import (
    ProjectStatus,
    ProjectMemberRole,
    ProjectMemberStatus,
    ProjectCreateRequest,
    ProjectUpdateRequest,
    ProjectResponse,
    ProjectSummary,
    ProjectDetail,
    ProjectListRequest,
    ProjectListResponse,
    ProjectStatusResponse,
    ProjectMemberResponse,
    ProjectMemberInviteRequest,
    ProjectMemberUpdateRequest,
    PaginationInfo,
    UserSummary,
    ProjectProgress,
    ProjectStatistics,
    ProjectActivity,
    ProjectError,
    ProjectNotFoundError,
    ProjectPermissionError,
    ProjectValidationError,
)

__all__ = [
    # Auth schemas
    "UserBase",
    "UserRegister", 
    "UserLogin",
    "UserResponse",
    "UserProfile",
    "TokenResponse",
    "LoginResponse",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "UpdateProfileRequest",
    "MessageResponse",
    "ErrorResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    
    # Project schemas
    "ProjectStatus",
    "ProjectMemberRole", 
    "ProjectMemberStatus",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectResponse",
    "ProjectSummary",
    "ProjectDetail",
    "ProjectListRequest",
    "ProjectListResponse",
    "ProjectStatusResponse",
    "ProjectMemberResponse",
    "ProjectMemberInviteRequest",
    "ProjectMemberUpdateRequest",
    "PaginationInfo",
    "UserSummary",
    "ProjectProgress",
    "ProjectStatistics",
    "ProjectActivity",
    "ProjectError",
    "ProjectNotFoundError",
    "ProjectPermissionError",
    "ProjectValidationError",
]
